name: Hourly Data Fetch

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Fetch prices-pve.json
        run: |
          echo "Fetching prices-pve.json..."
          wget https://raw.githubusercontent.com/RenoldzzZ/SPT-LiveFleaPriceDB/refs/heads/main/prices-pve.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add prices-pve.json
          git commit -m "Update prices-pve.json"
          git push
